### ISSUE TITLE
Username attribute in constroctor not working

### ISSUE THREAD

**Issue by sousa-andre** [kritzware/twitch-bot#22]
```javascript
const bot = new TwitchBot({
  username: 'Kappa_bot',
  oauth: 'oauth:<oauthcode>',
  channels: ['anndresousa']
})
The username attribute isn´t working
```

**Comment by kritzware** [comment]
What seems to be the problem you have? I can't seem to reproduce any errors, and the username parameter works as expected. 

Please make sure you're using the latest version of the bot, or provide more code/an example of what is going wrong.

**Comment by AnNdreSousa** [comment]
The username attribute don't change my bot username instaed the display
name is equals than mine

Em 14/02/2018 22:32, "kritzware" <notifications@github.com> escreveu:

What seems to be the problem you have? I can't seem to reproduce any
errors, and the username parameter works as expected.

Please make sure you're using the latest version of the bot, or provide
more code/an example of what is going wrong.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kritzware/twitch-bot/issues/22#issuecomment-365767106>,
or mute the thread

**Comment by kritzware** [comment]
The `username` parameter that you pass in must be a valid Twitch account that you own, and the `oauth` token must be for that Twitch account. The `username` parameter doesn't allow you to use any name as a bot, it must be the username of an account you own.

Use this tool (sign in with the bot account) to retrieve an oauth token: [https://twitchapps.com/tmi/](https://twitchapps.com/tmi/)
