### ISSUE TITLE
Channel joining/parting does not work properly

### ISSUE THREAD

**Issue by Hammster** [kritzware/twitch-bot#23]
Hi there,

I found a interesting issue in the latest feature:

- I join the channel '#hammster1911' but the bot has two elements in the channels property `['#hammster1911','hammster1911\r\n']`

- When i part from the channel it removes `hammster1911\r\n` but `hammster` remains in the array
`hammster1911\r\n` apperently originates from a channel join of a myself, where the second line is removed, according to this log
> "#hammster1911
> :hammster1911!hammster1911@hammster1911.tmi.twitch.tv "

- Upon joining the channel `#honestdangames` bot.say() will write in the remaining '#hammster' channel since it is not parted correctly.

I'm not 100% sure if this error originates from my code, you can check it out on GitHub though Hammster/twitch-chat#1

Btw this is for a Visual Studio Code extension that is using your library ;)

**Comment by kritzware** [comment]
Thanks for reporting this. That extension looks really cool, nice one! 👍

**Comment by anXieTyPB** [comment]
Could be an issue with the membership capability and the JOIN/PART for the bot user conflicting with JOIN/PART-messages, since the condition is the existence of a 'JOIN' in the string received from server, which is the case for both the generic and membership capabilities:

https://github.com/kritzware/twitch-bot/blob/master/lib/bot.js#L90

A quick and dirty workaround to test if thats really the root of the problem is commenting out the following line:
https://github.com/kritzware/twitch-bot/blob/master/lib/bot.js#L57

https://dev.twitch.tv/docs/irc#irc-generic-capabilities
https://dev.twitch.tv/docs/irc#twitch-irc-capability-membership

**Comment by anXieTyPB** [comment]
Nevermind, its about parsing the join/part-events. I implemented the parser for that and it doesnt take into account that there can be \r\n at the end of the message.

Will fix and submit PR.

**Comment by anXieTyPB** [comment]
https://github.com/kritzware/twitch-bot/pull/24

**Comment by kritzware** [comment]
This issue should be resolved now @Hammster! Make sure to upgrade the package from npm to the newest releast (1.2.3) 👍
